### ISSUE TITLE
Possible issue with luckiness calculation

### ISSUE THREAD

**Issue by jkjustjoshing** [jakearchibald/wordle-analyzer#21]
Here's an image of guess 3 from [this playthrough](https://wordle-analyzer.com/?seed=79&guesses=tlxxjfewmoprouatxhjhgurmc&hm=1)
<img width="800" alt="image" src="https://github.com/jakearchibald/wordle-analyzer/assets/813192/740d9d27-b425-45b9-b83d-b26bb3c26de0">

It shows my guess having 42 remaining possibilities as "Neutral" luck, and the AI guess having 16 remaining possibilities as "Very unlucky"

It seems to me that the AI's guess was luckier than mine.

**Comment by svivian** [comment]
I believe the luck is based on the average remaining words for that guess. So ‘laver’ would have 7.55 on average but in reality there were 16 (more than twice as many). For your guess it’s 27.15 -> 42 (less than twice as many). 

You could argue your guess was slightly unlucky instead of neutral but the AI was definitely unlucky there.

**Comment by jkjustjoshing** [comment]
I see what you mean. In this case, on average LAVER would do a better job at eliminating possible remaining words than it did. Since EMAIL is a worse guess, on average it wouldn't do as good a job at eliminating possible remaining words.

It's like me running a 20 second 100m sprint (neutral performance), and Usain Bolt running a 10.5 second 100m sprint (not great performance for him). His time is much better than mine, but compared to how he should have performed, it wasn't very impressive. In this example, I'm EMAIL and Usain Bolt is LAVER.
