### ISSUE TITLE
Bug in AI guess 

### ISSUE THREAD

**Issue by mkanavakatini** [jakearchibald/wordle-analyzer#9]
Potential bug today? AI opted for the wrong guess and ignored a letter that it knew and should have made the difference.

- AI had 2 common words on guess 3 to choose from
- AI knew that N was a correct letter
- only one common word had the letter N
- AI picked the other word 

https://wordle-analyzer.com/?seed=46&guesses=odmyssfdctqbzvydvoiz&hm=1

![Screenshot_20220303-004520_Brave](https://user-images.githubusercontent.com/13248401/156474823-a4cbb2ec-5367-4318-9d54-2b3813192632.jpg)

**Comment by paoloricciuti** [comment]
It's not exactly like this: the first playthrough is what AI would've done if it was in your shoes. Basically each new Guess of yours the AI act like if it had previosuly made all the same guesses as you did.

So it didn't actually know that N was a present letter because you didn't play TRONC but ROUGH.

After your guesses as you can see there's the AI Guesses that show how the AI would've played from start to the end.

**Comment by mkanavakatini** [comment]
Ahh I see, makes much more sense then! Thanks for the explanation 😊
